# Generated by Django 4.2.1 on 2023-06-04 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_orderdetails_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 19, 32, 28, 438027, tzinfo=datetime.timezone.utc)),
        ),
    ]
